const yachts = [
    {
        id: 1,
        slug: "armonia-38",
        name: "Armonia 38",
        image: "/images/yacht-1.webp",
        images: [
            "/images/yacht-1.webp",
            "/images/yacht-2.webp",
            "/images/yacht-3.webp",
        ],
        location: "Athens Marina",
        pricePerDay: 2250,
        pricePerHour: 320,
        guests: 10,
        cabins: 3,
        crew: 2,
        lengthFt: 38,
        speedKnots: 27,
        fuelIncluded: true,
        rating: 4.9,
        trips: 118,
        description:
            "Elegant day-cruiser for island hopping with sun deck, dining lounge, and premium sound. Crafted for private escapes with smooth handling, modern comforts, and memorable views.",
        features: [
            "Snorkeling Gear",
            "Bluetooth Audio",
            "Open Bar",
            "Sunbeds",
            "Air Conditioning",
            "Wi-Fi",
        ],
    },
    {
        id: 2,
        slug: "aegean-star-42",
        name: "Aegean Star 42",
        image: "/images/yacht-2.webp",
        images: [
            "/images/yacht-2.webp",
            "/images/yacht-3.webp",
            "/images/yacht-1.webp",
        ],
        location: "Mykonos Port",
        pricePerDay: 2850,
        pricePerHour: 390,
        guests: 12,
        cabins: 4,
        crew: 3,
        lengthFt: 42,
        speedKnots: 30,
        fuelIncluded: false,
        rating: 4.8,
        trips: 94,
        description:
            "Luxury yacht built for private parties and sunset routes with generous deck zones, premium audio, and a seamless cruising experience from port to hidden bays.",
        features: ["Jacuzzi", "Wi-Fi", "Paddle Boards", "Premium Snacks"],
    },
    {
        id: 3,
        slug: "blue-escape-46",
        name: "Blue Escape 46",
        image: "/images/yacht-3.webp",
        images: [
            "/images/yacht-3.webp",
            "/images/yacht-1.webp",
            "/images/yacht-2.webp",
        ],
        location: "Santorini Bay",
        pricePerDay: 3350,
        pricePerHour: 460,
        guests: 14,
        cabins: 4,
        crew: 3,
        lengthFt: 46,
        speedKnots: 29,
        fuelIncluded: true,
        rating: 5.0,
        trips: 67,
        description:
            "Flagship charter yacht designed for premium moments with panoramic views, expansive lounge areas, and a polished onboard service ideal for special events.",
        features: ["Onboard Chef", "Tender Boat", "Wakeboard", "Drone Photos"],
    },
    {
        id: 4,
        slug: "ionian-pearl-40",
        name: "Ionian Pearl 40",
        image: "/images/yacht-1.webp",
        images: [
            "/images/yacht-1.webp",
            "/images/yacht-3.webp",
            "/images/yacht-2.webp",
        ],
        location: "Corfu Harbor",
        pricePerDay: 2480,
        pricePerHour: 345,
        guests: 11,
        cabins: 3,
        crew: 2,
        lengthFt: 40,
        speedKnots: 28,
        fuelIncluded: true,
        rating: 4.7,
        trips: 82,
        description:
            "Balanced comfort and performance for family charters, coastal swims, and private tours with practical amenities and a calm, refined cabin layout.",
        features: ["Family Package", "Cooler", "Fishing Kit", "Sunshade"],
    },
    {
        id: 5,
        slug: "cyclades-wave-44",
        name: "Cyclades Wave 44",
        image: "/images/yacht-2.webp",
        images: [
            "/images/yacht-2.webp",
            "/images/yacht-1.webp",
            "/images/yacht-3.webp",
        ],
        location: "Naxos Marina",
        pricePerDay: 3090,
        pricePerHour: 430,
        guests: 13,
        cabins: 4,
        crew: 3,
        lengthFt: 44,
        speedKnots: 31,
        fuelIncluded: false,
        rating: 4.9,
        trips: 76,
        description:
            "Modern charter yacht for long day routes with confident handling, spacious social zones, and a thoughtful mix of comfort and performance details.",
        features: ["Sea Scooter", "Iced Drinks", "Towels", "Photo Package"],
    },
    {
        id: 6,
        slug: "mediterraneo-50",
        name: "Mediterraneo 50",
        image: "/images/yacht-3.webp",
        images: [
            "/images/yacht-3.webp",
            "/images/yacht-2.webp",
            "/images/yacht-1.webp",
        ],
        location: "Rhodes Marina",
        pricePerDay: 4200,
        pricePerHour: 580,
        guests: 16,
        cabins: 5,
        crew: 4,
        lengthFt: 50,
        speedKnots: 33,
        fuelIncluded: false,
        rating: 4.9,
        trips: 51,
        description:
            "Large luxury motor yacht tailored for VIP groups, celebrations, and full-day adventures with elevated finishes and concierge-grade hosting.",
        features: ["VIP Lounge", "Jet Ski", "Chef Menu", "Concierge"],
    },
];

export function getYachtBySlug(slug) {
    return yachts.find((item) => item.slug === slug) || null;
}

export function getAllYachtSlugs() {
    return yachts.map((item) => item.slug);
}

export { yachts };
