import Navbar from "@/components/Navbar";
import DevelopedBy from "@/components/home/DevelopedBy";
import Footer from "@/components/home/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Blue Escape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=""
    >
      <body className={inter.className}>
        <Navbar />

        <main className='flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]'>
          <div className='flex-1 flex flex-col h-full'>
            {children}
          </div>
        </main>

        <Footer />
        <DevelopedBy />
      </body>
    </html >
  );
}